#!/usr/bin/env bash

# Consistency Check Wrapper
# Executes linting, style checking, formatting, accessibility analysis and token verification.
# Generated by Antigravity – Ulpiano CCO consistency plan.

# This script is now a thin wrapper that delegates to the PowerShell version on Windows.
# On non‑Windows systems it will fall back to the original Bash implementation.

if [[ "${OSTYPE}" == "msys"* || "${OSTYPE}" == "cygwin"* || "${OSTYPE}" == "win32"* ]]; then
  # Windows – run PowerShell script located in the artifacts directory.
  pwsh -NoProfile -ExecutionPolicy Bypass -File "$(dirname "$0")/../.gemini/antigravity-ide/brain/2a8d61f6-b048-49b6-a8ee-5cc497213b32/consistency_check_ps.ps1"
else
  # Original Bash implementation (kept for Linux/macOS environments)
  echo "=== Running ESLint ==="
  if command -v eslint >/dev/null 2>&1; then eslint . --ext .js,.jsx,.ts,.tsx || true; else echo "ESLint not installed – skipping"; fi
  echo "=== Running Stylelint ==="
  if command -v stylelint >/dev/null 2>&1; then stylelint "**/*.{css,scss,html}" || true; else echo "Stylelint not installed – skipping"; fi
  echo "=== Running Prettier check ==="
  if command -v prettier >/dev/null 2>&1; then prettier --check "**/*.{js,jsx,ts,tsx,css,scss,html,md}" || true; else echo "Prettier not installed – skipping"; fi
  echo "=== Running axe-core (HTML) ==="
  if command -v axe-cli >/dev/null 2>&1; then axe-cli index.html --exclude "node_modules" || true; else echo "axe-cli not installed – skipping"; fi
  echo "=== Optimizing SVGs with svgo ==="
  if command -v svgo >/dev/null 2>&1; then svgo -f svg || true; else echo "svgo not installed – skipping"; fi
  echo "=== Verifying Design System Tokens ==="
  python3 scripts/verify_tokens.py || true
  echo "=== Consistency check completed ==="
fi

# Consistency Check Wrapper
# Executes linting, style checking, accessibility analysis and token verification.
# Generated by Antigravity – Ulpiano CCO consistency plan.

# Exit on any error
set -e

echo "=== Running ESLint ==="
if command -v eslint >/dev/null 2>&1; then
  eslint . --ext .js,.jsx,.ts,.tsx || true
else
  echo "ESLint not installed – skipping"
fi

echo "=== Running Stylelint ==="
if command -v stylelint >/dev/null 2>&1; then
  stylelint "**/*.{css,scss,html}" || true
else
  echo "Stylelint not installed – skipping"
fi

echo "=== Running Prettier check ==="
if command -v prettier >/dev/null 2>&1; then
  prettier --check "**/*.{js,jsx,ts,tsx,css,scss,html,md}" || true
else
  echo "Prettier not installed – skipping"
fi

echo "=== Running axe-core (HTML) ==="
# Using node script axe-cli if available
if command -v axe-cli >/dev/null 2>&1; then
  axe-cli index.html --exclude "node_modules" || true
else
  echo "axe-cli not installed – skipping"
fi

echo "=== Optimizing SVGs with svgo ==="
if command -v svgo >/dev/null 2>&1; then
  svgo -f svg || true
else
  echo "svgo not installed – skipping"
fi

echo "=== Verifying Design System Tokens ==="
python3 scripts/verify_tokens.py || true

echo "=== Consistency check completed ==="
